pipeline:
  build:
    image: syldexia/ubuntu-clang:latest
    pull: true
    commands:
      - make

  test:
    image: syldexia/ubuntu-clang:latest
    commands:
      - make dev
      - make test-verbose

  coverage:
    image: syldexia/ubuntu-clang:latest
    secrets: [ codecov_token ]
    commands:
      - make coverage
      - bash -c "bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN"
