pipeline:
  build:
    image: syldexia/ubuntu-clang:latest
    pull: true
    commands:
      - make

  test:
    image: syldexia/ubuntu-clang:latest
    commands:
      - make dev
      - make test

  coverage:
    image: syldexia/ubuntu-clang:latest
    secrets: [ codecov_token ]
    commands:
      - (mkdir -p build && cd build && cmake -D BUILD_TESTS=1 -D TEST_COVERAGE=1 .. && make)
      - make test
      - make coverage | sed '1d;$d' > build/coverage.txt
      - bash -c "bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN"

